version: 2

references:

  repo_container_config: &repo_container_config
    docker:
      - image: woahbase/alpine-android:x86_64
    working_directory: /home/${USER}/project/

  build_container_config: &build_container_config
    docker:
      - image: circleci/android:api-27-ndk
    working_directory: /home/${USER}/project/
    environment: &base_environment
      JVM_OPTS: -Xmx3200m

  repo_cache_paths: &repo_cache_paths
    paths:
      - "/home/${USER}/project/ZAndroid/"
  pub_cache_paths: &pub_cache_paths
    paths:
      - "/home/${USER}/project/ZAndroid/out/target/product/k5fpr/"

jobs:

  reposync:
    <<: *repo_container_config
    steps:
      - checkout
      - restore_cache:
          key: phantom-repo-Lineage-151-$(date +%Y%m%d)
          #<<: *repo_cache_key
      - run:
          name: Set Git Repo and Sync the Repository on Alpine
          command: |
            cd /home/${USER}/project/
            if [ ! -d "ZAndroid" ] ; then
                echo ${USER}
                echo ${PWD}
                DIR=${PWD}

                apk add --update --no-cache --purge -uU bash alpine-sdk make sudo

                sed -ie 's/^root::/root:!:/' /etc/shadow" || echo "Passwordless Root Mode error!"

                mkdir ~/bin ; echo ~/bin || echo "bin folder pre-existing"
                sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://github.com/akhilnarang/repo/raw/master/repo
                sudo chmod a+x /usr/local/bin/repo
                PATH=~/bin:/usr/local/bin:$PATH && echo $PATH

                git config --global user.email $GitHubMail && git config --global user.name $GitHubName
                git config --global color.ui true

                cd /home/${USER}/project/

                mkdir ZAndroid && cd ZAndroid

                echo "Initialize the repo data fetching"
                repo init -q -u https://github.com/LineageOS/android.git -b lineage-15.1
                echo "Sync it up ..."
                sudo repo sync -c -f -q --force-sync --no-clone-bundle --no-tags -j36
                sleep 2
                echo "The size of Repo is --" && du -sh .repo
                sudo chown -fR .repo
                rm -rf .repo/
                echo "Space taken by Files -- " && du -sh *
            else
                echo "ZAndroid Directory Found from Cache!" && sleep 2
            fi
          no_output_timeout: 12m
      - save_cache:
          key: phantom-repo-Lineage-151-$(date +%Y%m%d)
          <<: *repo_cache_paths

  builder:
    <<: *build_container_config
    steps:
      - checkout
      - run:
          name: Setup Some Apps required for the Build
          command: |
            sudo apt update -qy
            sudo apt install -qqy libssl-dev openjdk-8-jre openjdk-8-jdk \
            git curl libesd0-dev schedtool figlet libesd0-dev flex gperf libsdl1.2-dev squashfs-tools \
            pngcrush schedtool libxml2 libxml2-utils xsltproc lzop lib32z1-dev lib32ncurses5-dev pngquant \
            ncurses-dev texinfo gperf libtool automake gawk subversion expat python-all-dev bc libcloog-isl-dev libcap-dev \
            autoconf libgmp-dev pkg-config libmpc-dev libmpfr-dev lzma* w3m adb fastboot maven ncftp htop imagemagick \
            clang cmake axel re2c whiptail wput
            sleep 5
      - run:
          name: Git Config and ReLink Repo on Circle OpenJDK
          command: |
            git config --global user.email $GitHubMail && git config --global user.name $GitHubName
            git config --global color.ui true
            echo "Installing repo"
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://github.com/akhilnarang/repo/raw/master/repo
            sudo chmod a+x /usr/local/bin/repo
      - run:
          name: Get the Latest Make Tool by Building from Source
          command: |
            LATEST_MAKE_VERSION="4.2.1"
            if [[ "$(command -v make)" ]]; then
                makeversion="$(make -v | head -1 | awk '{print $3}')"
                if [[ "${makeversion}" != "${LATEST_MAKE_VERSION}" ]]; then
                    echo "Installing make ${LATEST_MAKE_VERSION} instead of ${makeversion}"
                    cd /tmp || exit 1
                    axel -k -a -n 10 https://ftp.gnu.org/gnu/make/make-"${LATEST_MAKE_VERSION}".tar.gz || axel -k -a -n 10 https://mirror.its.dal.ca/gnu/make/make-"${LATEST_MAKE_VERSION}".tar.gz
                    tar xzf /tmp/make-"${LATEST_MAKE_VERSION}".tar.gz
                    cd /tmp/make-"${LATEST_MAKE_VERSION}" || exit 1
                    ./configure
                    curl https://raw.githubusercontent.com/akhilnarang/scripts/master/patches/make-glibc_alloc_fix.patch | patch -p1
                    bash ./build.sh
                    sudo install ./make /usr/local/bin/make
                fi
            cd /tmp || exit 1
            rm -rf /tmp/make-"${LATEST_MAKE_VERSION}"{,.tar.gz}
            fi
      - run:
          name: Setup CCache and Ninja by Making them from Source 
          command: |
            echo "Installing CCache"
            cd /tmp || exit 1
            git clone git://github.com/akhilnarang/ccache.git
            cd ccache || exit 1
            ./autogen.sh
            ./configure --disable-man
            make -j"$(nproc)"
            sudo make install
            export 'USE_CCACHE=1' >> ~/.bashrc
            export 'CCACHE_COMPRESS=1' >> ~/.bashrc
            . ~/.bashrc
            /usr/local/bin/ccache -M 30G
            /usr/local/bin/ccache -C
            echo "Installing Ninja"
            cd /tmp || exit 1
            git clone git://github.com/akhilnarang/ninja.git
            cd ninja || exit 1
            ./configure.py --bootstrap
            sudo install ./ninja /usr/local/bin/ninja
            cd /tmp || exit 1
            rm -rf ccache ninja
      - run:
          name: Setup the New Android SDK on a Linux System"
          command: |
            TOOLS_URL="https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip"
            ZIP_NAME=$(printf '%s\n' "${TOOLS_URL##*/}")
            rm -rf /opt/android/sdk/*
            sudo mkdir -p /opt/android/sdk || echo "'/opt/android/sdk' dir is already there"
            cd /opt/android/sdk
            if axel -k -a -n 10 "${TOOLS_URL}"; then
                unzip -qqo "${ZIP_NAME}"
            else
                exit 1
            fi
            if [ ! -f ~/.android/repositories.cfg ] ; then
                touch ~/.android/repositories.cfg
                echo '### User Sources for Android SDK Manager' > ~/.android/repositories.cfg
            fi
            rm "${ZIP_NAME}"
            echo "ANDROID_HOME ENV is --" && echo ${ANDROID_HOME}
            source ~/.bashrc
            sleep 2
            echo "The PATH ENV is --" && echo $PATH && echo ""
            echo "Updating SDK Manager"
            yes | "${ANDROID_HOME}"/tools/bin/sdkmanager --licenses && yes | "${ANDROID_HOME}"/tools/bin/sdkmanager --update
            echo "Adding build-tools and platform-tools"
            "${ANDROID_HOME}"/tools/bin/sdkmanager 'build-tools;27.0.3' 'platform-tools' 'tools' 'platforms;android-27' || echo "sdkman tools install failed!"
            sleep 2
            echo ">>> Initial Disc Space is" && df -hlT
          no_output_timeout: 12m
      - restore_cache
          key: phantom-repo-Lineage-151-$(date +%Y%m%d)
          #<<: *repo_cache_key
      - run:
          name: Get Device Sources on place
          command: |
            cd /home/${USER}/project/
            if [ -d "ZAndroid" ] ; then
                echo "ZAndroid Folder Pre-exist through Cache."
            else
                echo "Fatal Error! ZAndroid Directory Not Found!" && sleep 2 && exit 1
            fi
            sudo chown -fR circleci:circleci *
            sudo git clone https://github.com/mohancm/android_kernel_lenovo_A7010a48 kernel/lenovo/k5fpr -b oreo
            sudo git clone https://github.com/SahilSonar/android_device_lenovo_k5fpr device/lenovo/k5fpr -b lineage-15.1
            sudo git clone https://github.com/SahilSonar/android_vendor_lenovo_k5fpr vendor/lenovo/k5fpr -b lineage-15.1
            sudo chown -fR circleci:circleci kernel
            sudo chown -fR circleci:circleci device
            sudo chown -fR circleci:circleci vendor
            echo "Apply Patches"
            cd device/lenovo/k5fpr/patches/
            chmod +x *.sh
            bash install.sh
            cd ../../../..
            echo ">>> How much space taken by checked-out files?" && du -sh /home/circleci/project/Zandroid
            echo ">>> Primary Disc Space is now --- " && df -hlT
            ls -la .
          no_output_timeout: 8m
      - run:
          name: Build the LineageOS
          command: |
            cd /home/${USER}/project/ZAndroid
            export ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx3200m"
            echo "Environment Setup"
            . build/envsetup.sh
            echo "Lunching --- "
            lunch lineage_k5fpr-userdebug
            sleep 2
            echo "Brunching, Umm.. --- "
            brunch lineage_k5fpr-userdebug
            sleep 2
          no_output_timeout: 25m
      - save_cache:
          key: phantom-pub-{{ CIRCLE_WORKFLOW_ID }}
          <<: *pub_cache_paths

  publish:
    <<: *repo_container_config
    steps:
      - checkout
      - restore_cache
          key: phantom-pub-{{ CIRCLE_WORKFLOW_ID }}
      - run:
          name: Publish whatever is made
          command: |
            echo ${USER}
            echo ${PWD}
            DIR=${PWD}
            apk add --update --no-cache --purge -uU bash alpine-sdk sudo wput
            cd /home/${USER}/project/
            if [ -d "ZAndroid" ] ; then
                echo "ZAndroid Folder Pre-exist through Cache."
                if [ -d "ZAndroid/out/target/product/k5fpr/"] ; then 
                    echo "Product Output Found"
                else 
                    echo "DIE!"
                fi
            else
                echo "Fatal Error! ZAndroid Directory Not Found!" && sleep 2 && exit 1
            fi
            cd out/target/product/k5fpr/
            echo "list all the files"
            ls -la */
            echo ""Start upload files
            for file in *; do wput $file ftp://"$FTPUser":"$FTPPass"@"$FTPHost"//Test_ZAndroid/Lenovo_k5fpr/ ; done
          no_output_timeout: 12m
            
workflows:
  version: 2

  build:
    jobs:
      - reposync
      - builder:
          requires:
            - reposync
      - publish:
          requires:
            - builder
